extends Node

const root = {
	'0-0': preload("res://assets/dominos_ui/0-0.tres"),
	'0-1': preload("res://assets/dominos_ui/0-1.tres"),
	'0-2': preload("res://assets/dominos_ui/0-2.tres"),
	'0-3': preload("res://assets/dominos_ui/0-3.tres"),
	'0-4': preload("res://assets/dominos_ui/0-4.tres"),
	'0-5': preload("res://assets/dominos_ui/0-5.tres"),
	'0-6': preload("res://assets/dominos_ui/0-6.tres"),
	'1-1': preload("res://assets/dominos_ui/1-1.tres"),
	'1-2': preload("res://assets/dominos_ui/1-2.tres"),
	'1-3': preload("res://assets/dominos_ui/1-3.tres"),
	'1-4': preload("res://assets/dominos_ui/1-4.tres"),
	'1-5': preload("res://assets/dominos_ui/1-5.tres"),
	'1-6': preload("res://assets/dominos_ui/1-6.tres"),
	'2-2': preload("res://assets/dominos_ui/2-2.tres"),
	'2-3': preload("res://assets/dominos_ui/2-3.tres"),
	'2-4': preload("res://assets/dominos_ui/2-4.tres"),
	'2-5': preload("res://assets/dominos_ui/2-5.tres"),
	'2-6': preload("res://assets/dominos_ui/2-6.tres"),
	'3-3': preload("res://assets/dominos_ui/3-3.tres"),
	'3-4': preload("res://assets/dominos_ui/3-4.tres"),
	'3-5': preload("res://assets/dominos_ui/3-5.tres"),
	'3-6': preload("res://assets/dominos_ui/3-6.tres"),
	'4-4': preload("res://assets/dominos_ui/4-4.tres"),
	'4-5': preload("res://assets/dominos_ui/4-5.tres"),
	'4-6': preload("res://assets/dominos_ui/4-6.tres"),
	'5-5': preload("res://assets/dominos_ui/5-5.tres"),
	'5-6': preload("res://assets/dominos_ui/5-6.tres"),
	'6-6': preload("res://assets/dominos_ui/6-6.tres"),
}
